### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by HollieHonich** [fengalin/jstation-controller#41]
Hello Fengalin! 
First I have to say I am very sorry to probably starting a disscussion this way.
Unfortunately I am absolutely new to this.
I have a MacBook Pro (Retina, 15', Mitte 2015) running Monterey 12.5.
I am clueless on how to install and use the
[jstation-controller-0.3.1.macos.tar.gz]
4.39 MB
Feb 1, 2023
on my machine. 
Can you please let me know how to do that.
I still have tons of presets, old software version for Mac and Win and close to everything which ever has been released on their page. 
I would love to use my old JStation with my Mac - ideally using my old presets.
Please let me know. I would even be willing to discuss through a different platform (Email, Chat, Facebook, Instagram whatever).
Thanks in advance for picking up the oportunity to keep such a great toy alive!

With best regards,
Holger

PS: I even have a Mooer GE200 if comparison might be needed.

**Comment by fengalin** [comment]
Hello Holger!

The file `jstation-controller-0.3.1.macos.tar.gz` you can download [from the release page](https://github.com/fengalin/jstation-controller/releases/tag/0.3.1) is a compressed archive. I think you should be able to extract its content by double-clicking the file once you downloaded it. Otherwise, you will probably need to open a command prompt, uncompress it with `gunzip jstation-controller-0.3.1.macos.tar.gz` & untar it with `tar -x jstation-controller-0.3.1.macos.tar`. Search for `macos decompress tar gz` for more details.

Whatever the method, you should get a new `jstation-controller-0.3.1.macos` directory with 3 files:

* jstation-controller
* LICENSES.html
* README.md

Double-clicking `jstation-controller` should be enough to launch the application, which will try to connect to your J-Station and download its presets.

That being said, as far as I know, nobody has ever tested it on macOS yet. I used cross platform libraries, developed it on linux and it just worked the first time I tried it on Windows. I can't guarantee it will run on macOS as is, however I'd be happy to iterate with you to get it to work.

If the application shows the UI but can't find the J-Station, please take a look at the Troubleshooting section in the `README.md` file.

Also note the following limitation: I didn't implement loading/storing the presets from/to files. I did it in a [previous iteration in python](https://github.com/fengalin/gstation-edit) though (only available for linux).

Best regards,

François

**Comment by HollieHonich** [comment]
Hi Francois.

Thanks a lot for your nice, fast reply and the offer you made.
Unzipping isn't a problem at all. 
So I connected my Jstation with FW 2.0 (used a MIDI-jack to USB adapter cable to do so) to my mac and doubleclicked the jstation-controller (I even ran it via sudo) but whatever I do, I always end up with the message below.
Does that bring some light into the situation?

/Downloads/jstation-controller-0.3.1.macos/jstation-controller ; exit;
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `iced_wgpu::triangle::gradient pipeline`
    Internal error in VERTEX | FRAGMENT | VERTEX_FRAGMENT shader: new_render_pipeline_state: "Compiler encountered an internal error"

', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.14.2/src/backend/direct.rs:2403:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by HollieHonich** [comment]
out of curiosity, I am working in the software business, closely with a dev, that also codes synthesizer stuff...I thought about asking him for help in terms of importing/exporting/loading/writing presets...due to this, can you let me know which programming language you used to do the jstation-controller app?

**Comment by fengalin** [comment]
Hi Hoger,

You seem to be facing a [known issue with `wgpu`](https://github.com/gfx-rs/wgpu/issues/4817). According to [this message](https://github.com/gfx-rs/wgpu/issues/4817#issuecomment-1903876474):

> this is probably a driver bug that happens later when compiling the Metal IR to GPU instructions

We will probably need to wait until the investigation leads somewhere.

In the meantime, I started updating the dependencies to the most recent I could easily. Another upgrade could be possible, but I would need to update [`iced_audio`](https://github.com/iced-rs/iced_audio) first. I'll see if I can find some time later this week.

I took this opportunity to generate a version which depends on differente rendering backends. Could you try the binaries in the following archive and tell me if it works any better?

[jstation-controller-ab6a06c-macos.zip](https://github.com/fengalin/jstation-controller/files/14084726/jstation-controller-ab6a06c-macos.zip)

* The one ending in `wgpu` uses the same backend as before, however I upgraded it to a newer version. I doubt it fixes the issue, but I think it's still worth the try.
* The one ending in [`glow`](https://github.com/iced-rs/iced/tree/0.9/glow) uses an OpenGL backend. Maybe you will have better luck with that one. It might require OpenGL 3.0+ libraries installed though.

Re. the language I used: this version is developed in Rust and the previous one I mentioned before (which supports loading / saving preset from / to files) was developed in Python.

**Comment by HollieHonich** [comment]
Hi François!

Thanks a LOT! The glow version finally worked. Really great work! Still can't believe it worked that well.
Switching the presets via software ... just wow. 

Any other idea on how to make importing or loading presets?
Can't I just put them into the same rootfolder like you do(?) with the factory ones?

I mean I still would love to see them being able to be stored. Ansolutely no way to get to there? 
As said before I have some hardware programmers friends who might be able to help to jzst store / reload.
Probably even based on your ideas. I would need to ask...

BR,
HoJo

**Comment by HollieHonich** [comment]
<img width="1440" alt="Bildschirmfoto 2024-01-29 um 22 22 03" src="https://github.com/fengalin/jstation-controller/assets/157842512/6514a160-8939-4532-8f6a-c2d2c6ec5aa2">

**Comment by HollieHonich** [comment]
<img width="1423" alt="Bildschirmfoto 2024-01-29 um 22 24 37" src="https://github.com/fengalin/jstation-controller/assets/157842512/7542dc5d-cdd7-45b8-a804-98d28d6fcd83">

**Comment by fengalin** [comment]
Awesome! Great to see the application running on macOS!

I'll make a new release with the glow version as an option. But first, I'd like to take a look at the errors I can see on your terminal. Could you redirect the output to a file and attach it here please? I could spot oversized program names detected. It might be due to an off-by-one check, need to check.

Out of curiosity, did you try the new wgpu version?

I'll probably implement the preset import / restore, that's what's missing for the application to be full featured. I just can't tell you when.

**Comment by fengalin** [comment]
I also notice a scrollbar on the effect & preset panels. Do they appear when you launch the application or did you resize the window?

**Comment by fengalin** [comment]
Hi Holger,

Re. the errors logged in your terminal, I can confirm the failure is due to names being more than 20 bytes long, which I thought was the limit. So I'm considering relaxing it. How did you name these presets? Did you use the official application JStation-Edit?

**Comment by fengalin** [comment]
Did more tests, 40 bytes should be the limit the OneProgramResp can handle actually. I'll use this limit now.

**Comment by HollieHonich** [comment]
Thanks again for all the effort spent!
In regards to the scrollbar, that has been caused by the changed window size, I did manually.

Yup, right, my guees as well, the namelength caused the parsing issues. I changed them using the Jedit program on using an old win7 VM. 

Anyway loading and adjusting and storing would be the real feature needed. I know its a BIG ask, but thats how it is.
You're a smart guy, so you know, this is the feature that everybody uses in all programs.

I thought I saw another issue, that amp and cab selection wasn't recalled / sent correctly, but it turned out to be not reproducible. 

I have so much stuff by and for the JStation. Please let me know if you are interested. Manuals, software, firmware, presets, banks, lists etc

Thanks again. Appreciate your effort.

**Comment by fengalin** [comment]
@HollieHonich: fyi new release with packages: https://github.com/fengalin/jstation-controller/releases/tag/0.3.2

> I thought I saw another issue, that amp and cab selection wasn't recalled / sent correctly

Please open an issue if you manage to reproduce it again.
